services:
  ##############################
  # ルータ設定
  ##############################
  r0:
    image: frrouting/frr:latest
    privileged: true
    volumes:
      - ./r0:/etc/frr
    networks:
      sapporo:
        ipv4_address: 192.168.100.200
      r0-r1:
        ipv4_address: 172.16.101.1
      r0-r2:
        ipv4_address: 172.16.102.1
      r0-r3:
        ipv4_address: 172.16.103.1
    sysctls:
      net.ipv4.ip_forward: 1
    command: ["bash", "-c", "/usr/lib/frr/frrinit.sh start && tail -f /dev/null"]
  r1:
    image: frrouting/frr:latest
    privileged: true
    volumes:
      - ./r1:/etc/frr
    networks:
      otaru:
        ipv4_address: 192.168.101.200
      r0-r1:
        ipv4_address: 172.16.101.200
    sysctls:
      net.ipv4.ip_forward: 1
    command: ["bash", "-c", "/usr/lib/frr/frrinit.sh start && tail -f /dev/null"]
  r2:
    image: frrouting/frr:latest
    privileged: true
    volumes:
      - ./r2:/etc/frr
    networks:
      asahikawa:
        ipv4_address: 192.168.102.200
      r0-r2:
        ipv4_address: 172.16.102.200
    sysctls:
      net.ipv4.ip_forward: 1
    command: ["bash", "-c", "/usr/lib/frr/frrinit.sh start && tail -f /dev/null"]
  r3:
    image: frrouting/frr:latest
    privileged: true
    volumes:
      - ./r3:/etc/frr
    networks:
      hakodate:
        ipv4_address: 192.168.103.200
      r0-r3:
        ipv4_address: 172.16.103.200
    sysctls:
      net.ipv4.ip_forward: 1
    command: ["bash", "-c", "/usr/lib/frr/frrinit.sh start && tail -f /dev/null"]

  ##############################
  # DNS
  ##############################
  dns-primary:
    build:
      context: ./dns-primary
    cap_add:
      - NET_ADMIN
    networks:
      sapporo:
        ipv4_address: 192.168.100.100

  ##############################
  # SMTP
  ##############################
  smtp-otaru:
    build:
      context: ./smtp-otaru
    cap_add:
      - NET_ADMIN
    networks:
      otaru:
        ipv4_address: 192.168.101.30
    dns:
      - 192.168.100.100
    dns_search:
      - otaru.test

  smtp-hakodate:
    build:
      context: ./smtp-hakodate
    cap_add:
      - NET_ADMIN
    networks:
      hakodate:
        ipv4_address: 192.168.103.30
    dns:
      - 192.168.100.100
    dns_search:
      - hakodate.test

  ##############################
  # IMAP
  ##############################
  imap-otaru:
    build:
      context: ./imap-otaru
    cap_add:
      - NET_ADMIN
    networks:
      otaru:
        ipv4_address: 192.168.101.31
    dns:
      - 192.168.100.100
    dns_search:
      - otaru.test

  imap-hakodate:
    build:
      context: ./imap-hakodate
    cap_add:
      - NET_ADMIN
    networks:
      hakodate:
        ipv4_address: 192.168.103.31
    dns:
      - 192.168.100.100
    dns_search:
      - hakodate.test

  ##############################
  # テスト用クライアント
  ##############################
  client-otaru:
    build:
      context: ./client-otaru
    cap_add:
      - NET_ADMIN
    networks:
      otaru:
        ipv4_address: 192.168.101.1
    dns:
      - 192.168.100.100
    dns_search:
      - otaru.test
    command: ["bash", "-c", "ip route add default via 192.168.101.200 && sleep infinity"]
    
  client-hakodate:
    build:
      context: ./client-hakodate
    cap_add:
      - NET_ADMIN
    networks:
      hakodate:
        ipv4_address: 192.168.103.1
    dns:
      - 192.168.100.100
    dns_search:
      - hakodate.test
    command: ["bash", "-c", "ip route add default via 192.168.103.200 && sleep infinity"]

  ##############################
  # テスト用WEBサーバ
  ##############################
  web:
    build:
      context: ./web
    cap_add:
      - NET_ADMIN
    networks:
      sapporo:
        ipv4_address: 192.168.100.102

##############################
# ネットワーク構成
##############################
networks:
  sapporo:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.250
  otaru:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 192.168.101.0/24
          gateway: 192.168.101.250
  asahikawa:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 192.168.102.0/24
          gateway: 192.168.102.250
  hakodate:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 192.168.103.0/24
          gateway: 192.168.103.250
  r0-r1:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.16.101.0/24
          gateway: 172.16.101.250
  r0-r2:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.16.102.0/24
          gateway: 172.16.102.250
  r0-r3:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.16.103.0/24
          gateway: 172.16.103.250
